### ISSUE TITLE
Add support for 'notice-alt' class

### ISSUE THREAD

**Issue by embolden** [embolden/admin-notice#1]
`wp-admin/css/common.css` has styling for a class called `notice-alt` that applies a muted background color the admin notice.

```css
.notice-success,
div.updated {
	border-left-color: #46b450;
}

.notice-success.notice-alt {
	background-color: #ecf7ed;
}

.notice-warning {
	border-left-color: #ffb900;
}

.notice-warning.notice-alt {
	background-color: #fff8e5;
}

.notice-error,
div.error {
	border-left-color: #dc3232;
}

.notice-error.notice-alt {
	background-color: #fbeaea;
}

.notice-info {
	border-left-color: #00a0d2;
}

.notice-info.notice-alt {
	background-color: #e5f5fa;
}
```
