### ISSUE TITLE
Add support for 'notice-large' class

### ISSUE THREAD

**Issue by embolden** [embolden/admin-notice#2]
`wp-admin/css/common.css` has styling for a `notice-large` class that applies extra padding.

```css
.notice-large {
	padding: 10px 20px;
}
```
